### ISSUE TITLE
Markup in script tags get highlighted as erroneous

### ISSUE THREAD

**Issue by jrjdavidson** [karuna/tera-vscode#29]
Possible duplicate of https://github.com/karuna/tera-vscode/issues/23 and https://github.com/karuna/tera-vscode/issues/22

If include some tera markup in a script, it gets highlighted as erroneous. Other places in that file, the markup is fine. I use this pattern to preload data along with the page. Not sure if this is a valid use, but though I'd flag it. 

```
  <script>  
    {% block js %}
    {% endblock js %}
  </script>
```
![image](https://github.com/user-attachments/assets/c133596c-6241-43bd-b4a8-4e6c071a1b27)

```
related log:
[{
	"resource": "/d:/UC Enterprise Dropbox/Jonathan Davidson/Work/antarctic weather stations/data_handler/templates/base.html.tera",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "Expression expected.",
	"source": "javascript",
	"startLineNumber": 416,
	"startColumn": 6,
	"endLineNumber": 416,
	"endColumn": 7
},{
	"resource": "/d:/UC Enterprise Dropbox/Jonathan Davidson/Work/antarctic weather stations/data_handler/templates/base.html.tera",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "';' expected.",
	"source": "javascript",
	"startLineNumber": 416,
	"startColumn": 14,
	"endLineNumber": 416,
	"endColumn": 16
},{
	"resource": "/d:/UC Enterprise Dropbox/Jonathan Davidson/Work/antarctic weather stations/data_handler/templates/base.html.tera",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "Expression expected.",
	"source": "javascript",
	"startLineNumber": 416,
	"startColumn": 18,
	"endLineNumber": 416,
	"endColumn": 19
},{
	"resource": "/d:/UC Enterprise Dropbox/Jonathan Davidson/Work/antarctic weather stations/data_handler/templates/base.html.tera",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "Expression expected.",
	"source": "javascript",
	"startLineNumber": 417,
	"startColumn": 6,
	"endLineNumber": 417,
	"endColumn": 7
},{
	"resource": "/d:/UC Enterprise Dropbox/Jonathan Davidson/Work/antarctic weather stations/data_handler/templates/base.html.tera",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "';' expected.",
	"source": "javascript",
	"startLineNumber": 417,
	"startColumn": 17,
	"endLineNumber": 417,
	"endColumn": 19
},{
	"resource": "/d:/UC Enterprise Dropbox/Jonathan Davidson/Work/antarctic weather stations/data_handler/templates/base.html.tera",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "Expression expected.",
	"source": "javascript",
	"startLineNumber": 417,
	"startColumn": 21,
	"endLineNumber": 417,
	"endColumn": 22
}]
```

**Comment by karuna** [comment]
works for me

![Image](https://github.com/user-attachments/assets/45f2240d-b0d6-4690-93af-a0f54c11334f)

**Comment by jrjdavidson** [comment]
Thanks for checking! I double checked with your minimal example and I still get the same error.

I had a look around to see what I could possibly be doing wrong and noticed this error in the extension host, possibly related?:
```
2025-04-14 13:23:21.955 [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
2025-04-14 13:23:22.023 [info] ExtensionService#_doActivateExtension karunamurti.tera, startup: false, activationEvent: 'onLanguage:html'
2025-04-14 13:23:22.026 [error] Activating extension karunamurti.tera failed due to an error:
2025-04-14 13:23:22.026 [error] Error: Cannot find module 'c:\Users\jrd92\.vscode\extensions\karunamurti.tera-0.0.9\lib\index.js'
Require stack:
- c:\Users\jrd92\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
	at n._resolveFilename (node:electron/js2c/utility_init:2:16068)
	at t._resolveFilename (file:///c:/Users/jrd92/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:183:22672)
	at Module._load (node:internal/modules/cjs/loader:1058:27)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Users/jrd92/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:197:1509)
	at t._load (file:///c:/Users/jrd92/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:183:22390)
	at i._load (file:///c:/Users/jrd92/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:24781)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at vV.xb (file:///c:/Users/jrd92/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:183:23710)
	at async Promise.all (index 0)
```

here is the content of C:\Users\jrd92\.vscode\extensions\karunamurti.tera-0.0.9:

![Image](https://github.com/user-attachments/assets/e45c7523-149a-4d32-a327-201cdce5c2b2)

I tried re-installing the extension in case that was the source of the error, but it didn't fix the error

**Comment by jrjdavidson** [comment]
Could this be related to #7 ?

**Comment by karuna** [comment]
hmm, weird the latest version is 0.1.0. but marketplace is 0.0.9

**Comment by karuna** [comment]
going to update and publish new one later
